/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  BookOpen, Sparkles, AlertCircle, RefreshCw, Layers, CheckCircle, 
  HelpCircle, Eye, HelpCircle as HelpIcon, ArrowRightLeft, BookMarked
} from 'lucide-react';
import { ClinicalBlock, PDFDocument, Flashcard } from '../types';

interface ModuloEstudioProps {
  blocks: ClinicalBlock[];
  documents: PDFDocument[];
  flashcards: Flashcard[];
  onGenerateStudyMaterial: (week: number, topic: string, content: string) => Promise<{
    sintesis: string;
    puntosFocalizados: string[];
    flashcards: { question: string; answer: string; explanation: string }[];
  }>;
}

export default function ModuloEstudio({
  blocks,
  documents,
  flashcards,
  onGenerateStudyMaterial
}: ModuloEstudioProps) {
  const [selectedBlockId, setSelectedBlockId] = useState<string>(blocks[0]?.id || '');
  const [selectedWeek, setSelectedWeek] = useState<number>(1);
  const [isGenerating, setIsGenerating] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  
  // Custom material generated by Gemini
  const [generatedMaterial, setGeneratedMaterial] = useState<{
    sintesis: string;
    puntosFocalizados: string[];
    flashcards: { question: string; answer: string; explanation: string }[] | null;
  } | null>(null);

  // Flip card states
  const [flippedCards, setFlippedCards] = useState<{ [key: string]: boolean }>({});

  const activeBlock = blocks.find(b => b.id === selectedBlockId);
  const blockWeeks = activeBlock ? activeBlock.weeks : [];

  // Sync selected week when active block changes
  useEffect(() => {
    if (blockWeeks.length > 0) {
      // Find the first week available in the block
      setSelectedWeek(blockWeeks[0]);
      setGeneratedMaterial(null);
      setFlippedCards({});
      setErrorMsg('');
    }
  }, [selectedBlockId]);

  const activeDoc = documents.find(d => d.week === selectedWeek);

  // Relevant flashcards for current week
  const relevantFlashcards = generatedMaterial?.flashcards 
    ? generatedMaterial.flashcards.map((fc, idx) => ({
        id: `gen-fc-${idx}`,
        topicId: `doc-w${selectedWeek}`,
        question: fc.question,
        answer: fc.answer,
        yield: 'HIGH-YIELD' as const,
        explanation: fc.explanation
      }))
    : flashcards.filter(fc => fc.topicId === activeDoc?.id);

  const handleGenerate = async () => {
    if (!activeDoc) return;
    setIsGenerating(true);
    setErrorMsg('');
    try {
      const result = await onGenerateStudyMaterial(
        activeDoc.week,
        activeDoc.topic,
        activeDoc.content
      );
      setGeneratedMaterial(result);
    } catch (err: any) {
      console.error(err);
      setErrorMsg(err.message || 'No se pudo conectar con el Tutor Clínico Gemini. Mostrando apuntes estáticos locales.');
    } finally {
      setIsGenerating(false);
    }
  };

  const toggleFlip = (cardId: string) => {
    setFlippedCards(prev => ({
      ...prev,
      [cardId]: !prev[cardId]
    }));
  };

  return (
    <div id="modulo-estudio-root" className="space-y-6">
      
      {/* Top Selectors Bar */}
      <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm space-y-4">
        <h3 className="font-sans font-bold text-slate-900 text-lg flex items-center gap-2">
          <Layers className="w-5 h-5 text-blue-600" /> Selector de Temarios UCS
        </h3>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="space-y-1">
            <label className="text-xs font-semibold text-slate-500 uppercase font-mono">Bloque Académico</label>
            <select
              value={selectedBlockId}
              onChange={(e) => setSelectedBlockId(e.target.value)}
              className="w-full text-sm p-3 rounded-xl border border-slate-200 bg-slate-50/50 hover:bg-slate-50 focus:outline-blue-500 font-sans font-semibold text-slate-800"
            >
              {blocks.map(b => (
                <option key={b.id} value={b.id}>
                  {b.name} ({b.priority})
                </option>
              ))}
            </select>
          </div>

          <div className="space-y-1">
            <label className="text-xs font-semibold text-slate-500 uppercase font-mono">Tema / Semana</label>
            <select
              value={selectedWeek}
              onChange={(e) => {
                setSelectedWeek(Number(e.target.value));
                setGeneratedMaterial(null);
                setFlippedCards({});
                setErrorMsg('');
              }}
              className="w-full text-sm p-3 rounded-xl border border-slate-200 bg-slate-50/50 hover:bg-slate-50 focus:outline-blue-500 font-sans font-semibold text-slate-800"
            >
              {blockWeeks.map(wk => {
                const doc = documents.find(d => d.week === wk);
                return (
                  <option key={wk} value={wk}>
                    Semana {wk}: {doc ? doc.topic : `Tema Especial ${wk}`}
                  </option>
                );
              })}
            </select>
          </div>

          <div className="flex items-end">
            <button
              id="btn-ai-generate"
              onClick={handleGenerate}
              disabled={isGenerating || !activeDoc}
              className="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 px-5 rounded-xl text-sm transition-all duration-200 flex items-center justify-center gap-2 active:scale-98 disabled:opacity-50 cursor-pointer shadow-md shadow-blue-500/10"
            >
              {isGenerating ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin text-blue-300" />
                  Sintetizando con Gemini...
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 text-blue-300" />
                  Personalizar Estudio con IA
                </>
              )}
            </button>
          </div>
        </div>
      </div>

      {errorMsg && (
        <div className="p-4 bg-amber-50 border border-amber-200 text-amber-900 rounded-xl text-xs flex gap-2">
          <AlertCircle className="w-4 h-4 flex-shrink-0 text-amber-600" />
          <div>
            <strong>Nota del Sistema:</strong> {errorMsg}
          </div>
        </div>
      )}

      {/* Main Study Panel */}
      {activeDoc ? (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          
          {/* Left panel: Synthesis and evaluation points */}
          <div className="lg:col-span-8 space-y-6">
            
            {/* Sintesis Clave Directa */}
            <div className="bg-white rounded-2xl p-6 md:p-8 border border-slate-200 shadow-sm space-y-6 relative">
              <div className="flex justify-between items-start">
                <div className="space-y-1">
                  <div className="text-xs font-semibold text-blue-600 font-mono uppercase">
                    Semana {activeDoc.week} — Fisiopatología y APS
                  </div>
                  <h2 className="text-xl md:text-2xl font-bold font-sans text-slate-900 leading-tight">
                    {activeDoc.topic}
                  </h2>
                </div>
                {generatedMaterial && (
                  <span className="inline-flex items-center gap-1 text-[11px] font-bold text-blue-700 bg-blue-100/50 border border-blue-200 px-2.5 py-1 rounded-full font-mono animate-pulse">
                    <Sparkles className="w-3 h-3 text-blue-500" /> IA Activa
                  </span>
                )}
              </div>

              <div className="prose prose-slate max-w-none text-slate-700 text-sm md:text-base leading-relaxed space-y-4">
                {generatedMaterial ? (
                  <p className="whitespace-pre-wrap">{generatedMaterial.sintesis}</p>
                ) : (
                  <>
                    <p className="font-semibold text-slate-900 bg-slate-50 p-4 rounded-xl border-l-4 border-l-blue-600 shadow-3xs">
                      {activeDoc.summary}
                    </p>
                    <p className="whitespace-pre-line text-slate-600 text-sm">{activeDoc.content}</p>
                  </>
                )}
              </div>

              <div className="pt-4 border-t border-slate-100 flex items-center justify-between text-xs text-slate-400 font-mono">
                <span>Robbins Patología 7ma / 10ma Edición</span>
                <span>UCS Morfofisiopatología I</span>
              </div>
            </div>

            {/* Puntos Focalizados UCS (Lo que van a preguntar) */}
            <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm space-y-4">
              <h4 className="font-sans font-bold text-slate-900 text-base flex items-center gap-2">
                <BookMarked className="w-5 h-5 text-amber-500" />
                Puntos Focalizados UCS (Lo que van a preguntar en el examen)
              </h4>
              <p className="text-xs text-slate-500 font-sans">
                Preguntas de patrón oficial y criterios estricto de Atención Primaria. Memoriza estos aspectos:
              </p>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {generatedMaterial?.puntosFocalizados ? (
                  generatedMaterial.puntosFocalizados.map((punto, i) => (
                    <div key={i} className="p-3 bg-slate-50/70 border border-slate-200/60 rounded-xl flex gap-2 text-xs text-slate-700 font-sans">
                      <span className="text-blue-600 font-mono font-bold mt-0.5">#{i+1}</span>
                      <p className="font-sans">{punto}</p>
                    </div>
                  ))
                ) : (
                  <>
                    <div className="p-3 bg-slate-50/70 border border-slate-200/60 rounded-xl flex gap-2 text-xs text-slate-700 font-sans">
                      <span className="text-blue-600 font-mono font-bold mt-0.5">#1</span>
                      <p>Clasificaciones estrictas de procesos: ej. células lábiles, estables o permanentes y ejemplos clínicos.</p>
                    </div>
                    <div className="p-3 bg-slate-50/70 border border-slate-200/60 rounded-xl flex gap-2 text-xs text-slate-700 font-sans">
                      <span className="text-blue-600 font-mono font-bold mt-0.5">#2</span>
                      <p>Diferencias microscópicas y macroscópicas claves: ej. necrosis por coagulación vs colicuativa, y sus órganos diana.</p>
                    </div>
                    <div className="p-3 bg-slate-50/70 border border-slate-200/60 rounded-xl flex gap-2 text-xs text-slate-700 font-sans">
                      <span className="text-blue-600 font-mono font-bold mt-0.5">#3</span>
                      <p>Mecanismo celular en la hipoxia: Falla de bombas de membrana, disminución de ATP y su traducción morfológica.</p>
                    </div>
                    <div className="p-3 bg-slate-50/70 border border-slate-200/60 rounded-xl flex gap-2 text-xs text-slate-700 font-sans">
                      <span className="text-blue-600 font-mono font-bold mt-0.5">#4</span>
                      <p>Marcadores analíticos e imagenológicos asociados para corroborar el proceso patológico ante el ASIC comunitario.</p>
                    </div>
                  </>
                )}
              </div>
            </div>

          </div>

          {/* Right panel: Flashcards de Memorización Rápida */}
          <div className="lg:col-span-4 space-y-6">
            <div className="bg-slate-900 rounded-2xl p-6 border border-slate-850 text-white shadow-xl space-y-4">
              <div className="space-y-1">
                <h3 className="font-sans font-bold text-white text-base flex items-center gap-2">
                  <HelpIcon className="w-5 h-5 text-blue-400" />
                  Flashcards High-Yield
                </h3>
                <p className="text-slate-400 text-xs leading-relaxed font-sans">
                  Haz clic en las tarjetas para girarlas y revelar los datos clínicos clave para memorizar rápidamente antes del examen.
                </p>
              </div>

              <div className="space-y-4">
                {relevantFlashcards.length > 0 ? (
                  relevantFlashcards.map((fc, i) => {
                    const isFlipped = !!flippedCards[fc.id];
                    return (
                      <div
                        key={fc.id}
                        onClick={() => toggleFlip(fc.id)}
                        className="cursor-pointer group relative h-48 w-full perspective"
                      >
                        {/* Interactive flippable card body */}
                        <div className={`relative w-full h-full text-center transition-all duration-500 transform-style preserve-3d ${
                          isFlipped ? 'rotate-y-180' : ''
                        }`}>
                          
                          {/* Front Side: Question */}
                          <div className="absolute inset-0 bg-slate-800 border border-slate-700 rounded-xl p-4 flex flex-col justify-between backface-hidden">
                            <div className="flex justify-between items-center text-[10px] font-mono text-blue-400 uppercase font-semibold">
                              <span>Tarjeta #{i + 1}</span>
                              <span className="bg-blue-500/20 px-1.5 py-0.5 rounded text-blue-300 border border-blue-500/20 font-sans">High-Yield</span>
                            </div>
                            <p className="text-xs md:text-sm font-semibold text-slate-100 flex-grow flex items-center justify-center p-2 leading-relaxed font-sans">
                              {fc.question}
                            </p>
                            <span className="text-[10px] text-slate-400 font-mono inline-flex items-center gap-1 justify-center">
                              <Eye className="w-3.5 h-3.5" /> Revelar Respuesta
                            </span>
                          </div>

                          {/* Back Side: Answer */}
                          <div className="absolute inset-0 bg-blue-950 border border-blue-900 rounded-xl p-4 flex flex-col justify-between rotate-y-180 backface-hidden">
                            <div className="text-[10px] font-mono text-blue-300 uppercase font-semibold">
                              Respuesta Oficial
                            </div>
                            <div className="flex-grow flex flex-col items-center justify-center space-y-2 p-2">
                              <p className="text-xs md:text-sm font-bold text-white leading-relaxed font-sans">
                                {fc.answer}
                              </p>
                              <p className="text-[10px] text-blue-300/80 leading-relaxed max-h-16 overflow-y-auto font-sans">
                                {fc.explanation}
                              </p>
                            </div>
                            <span className="text-[10px] text-blue-400 font-mono inline-flex items-center gap-1 justify-center">
                              <ArrowRightLeft className="w-3 h-3" /> Volver a Pregunta
                            </span>
                          </div>

                        </div>
                      </div>
                    );
                  })
                ) : (
                  <div className="p-6 text-center bg-slate-800/50 rounded-xl border border-slate-800/80 text-slate-400 text-xs font-sans">
                    No hay flashcards para este tema. Haz clic en "Personalizar Estudio con IA" para generarlas en tiempo real.
                  </div>
                )}
              </div>
            </div>
          </div>

        </div>
      ) : (
        <div className="text-center p-12 bg-white rounded-2xl border border-slate-200">
          <BookOpen className="w-12 h-12 text-slate-300 mx-auto mb-4" />
          <h4 className="font-sans font-bold text-slate-800">Cargar Sílabo para comenzar</h4>
          <p className="text-sm text-slate-500 max-w-sm mx-auto mt-1 font-sans">
            Por favor, procesa primero todos los documentos en la pestaña de Plan de Choque para habilitar el selector de materias.
          </p>
        </div>
      )}

    </div>
  );
}
